version: '3.7'

services:
  ssafy-pjt1:
    container_name: ssafy-pjt1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    networks:
      - ssafy-pjt1-backend   

  nginx:
    image: nginx
    restart: always
    volumes:
      - '.:/app/public/src/www/static'
      - './default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
      - ssafy-pjt1
    networks:
      - ssafy-pjt1-backend


  ssafy-pjt1-backend:
    container_name: ssafy-pjt1-backend
    build:
      context: /home/ubuntu/PJT1/s03p12a206/backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ssafypjt1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Rnehdduq6650!'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
networks: 
  ssafy-pjt1-backend:
    driver: bridge
volumes:
  my-db:

