version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '80:80'

  nginx:
    restart: always
    image: nginx:latest 
    ports:
      - '443:443'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - '/home/ubuntu/ssl/:/ssl/'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ssafypjt1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Rnehdduq6650!'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
